package com.snapmeal.report;
import com.snapmeal.common.*;import org.apache.poi.ss.usermodel.*;import org.apache.poi.xssf.usermodel.XSSFWorkbook;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.web.bind.annotation.*;import javax.servlet.http.HttpServletResponse;import java.io.IOException;import java.math.BigDecimal;import java.net.URLEncoder;import java.sql.Date;import java.time.LocalDate;import java.util.*;
@RestController @RequestMapping("/api/admin/reports")
public class ReportController {
    private final JdbcTemplate jdbc;public ReportController(JdbcTemplate jdbc){this.jdbc=jdbc;}
    @GetMapping("/overview") public ApiResponse<Map<String,Object>> overview(){Map<String,Object> out=new LinkedHashMap<>();out.put("turnover",jdbc.queryForObject("select coalesce(sum(amount),0) from orders where pay_status=1",BigDecimal.class));out.put("validOrders",jdbc.queryForObject("select count(*) from orders where status=5",Integer.class));out.put("users",jdbc.queryForObject("select count(*) from app_user",Integer.class));out.put("pendingOrders",jdbc.queryForObject("select count(*) from orders where status=2",Integer.class));return ApiResponse.ok(out);}
    @GetMapping("/turnover") public ApiResponse<List<Map<String,Object>>> turnover(@RequestParam(required=false)String begin,@RequestParam(required=false)String end){LocalDate b=begin==null?LocalDate.now().minusDays(6):LocalDate.parse(begin);LocalDate e=end==null?LocalDate.now():LocalDate.parse(end);return ApiResponse.ok(jdbc.queryForList("select cast(order_time as date) date,sum(amount) amount from orders where pay_status=1 and order_time>=? and order_time<? group by cast(order_time as date) order by date",Date.valueOf(b),Date.valueOf(e.plusDays(1))));}
    @GetMapping("/sales-top10") public ApiResponse<List<Map<String,Object>>> top10(){return ApiResponse.ok(jdbc.queryForList("select d.name,sum(d.number) number from order_detail d join orders o on o.id=d.order_id where o.pay_status=1 group by d.name order by number desc limit 10"));}
    @GetMapping("/export") public void export(HttpServletResponse response) throws IOException {response.setContentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");response.setHeader("Content-Disposition","attachment; filename*=UTF-8''"+URLEncoder.encode("运营数据报表.xlsx","UTF-8"));try(Workbook wb=new XSSFWorkbook()){Sheet sheet=wb.createSheet("运营数据");Row h=sheet.createRow(0);String[] headers={"订单号","下单时间","收货人","金额","支付状态","订单状态"};for(int i=0;i<headers.length;i++)h.createCell(i).setCellValue(headers[i]);List<Map<String,Object>> rows=jdbc.queryForList("select number,order_time,consignee,amount,pay_status,status from orders order by order_time desc");for(int i=0;i<rows.size();i++){Map<String,Object> data=rows.get(i);Row row=sheet.createRow(i+1);row.createCell(0).setCellValue(String.valueOf(Db.get(data,"number")));row.createCell(1).setCellValue(String.valueOf(Db.get(data,"order_time")));row.createCell(2).setCellValue(String.valueOf(Db.get(data,"consignee")));row.createCell(3).setCellValue(Double.parseDouble(String.valueOf(Db.get(data,"amount"))));row.createCell(4).setCellValue(((Number)Db.get(data,"pay_status")).intValue()==1?"已支付":"未支付");row.createCell(5).setCellValue(String.valueOf(Db.get(data,"status")));}for(int i=0;i<headers.length;i++)sheet.autoSizeColumn(i);wb.write(response.getOutputStream());}}
}
