package com.snapmeal.auth;
import com.snapmeal.common.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.web.bind.annotation.*; import javax.servlet.http.HttpServletRequest; import java.util.*;
@RestController @RequestMapping("/api")
public class AuthController {
    private final JdbcTemplate jdbc;private final TokenService tokens;public AuthController(JdbcTemplate jdbc,TokenService tokens){this.jdbc=jdbc;this.tokens=tokens;}
    @PostMapping("/admin/auth/login") public ApiResponse<Map<String,Object>> admin(@RequestBody LoginRequest req){List<Map<String,Object>> rows=jdbc.queryForList("select id,name,password,status from employee where username=?",req.username);if(rows.isEmpty()||!String.valueOf(Db.get(rows.get(0),"password")).equals(req.password))throw new BusinessException("用户名或密码错误");Map<String,Object> e=rows.get(0);if(Db.intValue(e,"status")==0)throw new BusinessException("账号已禁用");Map<String,Object> out=new HashMap<>();out.put("id",Db.get(e,"id"));out.put("name",Db.get(e,"name"));out.put("token",tokens.issue(Db.longValue(e,"id"),"ADMIN"));return ApiResponse.ok(out);}
    @PostMapping("/user/auth/login") public ApiResponse<Map<String,Object>> user(@RequestBody LoginRequest req){String method=req.loginMethod;if(!"PHONE".equals(method)&&!"WECHAT".equals(method))throw new BusinessException("请选择登录方式");String identity,nickname,phone;if("PHONE".equals(method)){if(req.phone==null||req.phone.trim().isEmpty())throw new BusinessException("请输入手机号码");phone=req.phone.trim();identity="phone:"+phone;nickname="手机体验用户";}else{phone=null;identity="wechat:demo-user";nickname="微信体验用户";}List<Map<String,Object>> rows=jdbc.queryForList("select id from app_user where openid=?",identity);long id;if(rows.isEmpty()){jdbc.update("insert into app_user(openid,nickname,phone,create_time) values(?,?,?,current_timestamp)",identity,nickname,phone);id=jdbc.queryForObject("select id from app_user where openid=?",Long.class,identity);}else{id=Db.longValue(rows.get(0),"id");jdbc.update("update app_user set nickname=?,phone=? where id=?",nickname,phone,id);}Map<String,Object> out=new HashMap<>();out.put("id",id);out.put("nickname",nickname);out.put("loginMethod",method);out.put("token",tokens.issue(id,"USER"));return ApiResponse.ok(out);}
    @GetMapping("/admin/auth/session") public ApiResponse<Map<String,Object>> adminSession(HttpServletRequest request){long id=((Number)request.getAttribute(AuthInterceptor.SUBJECT_ID)).longValue();Map<String,Object> out=new HashMap<>();out.put("id",id);out.put("valid",true);return ApiResponse.ok(out);}
    @GetMapping("/user/auth/session") public ApiResponse<Map<String,Object>> userSession(HttpServletRequest request){long id=((Number)request.getAttribute(AuthInterceptor.SUBJECT_ID)).longValue();Map<String,Object> user=jdbc.queryForMap("select id,nickname,openid from app_user where id=?",id);Map<String,Object> out=new HashMap<>();out.put("id",Db.get(user,"id"));out.put("nickname",Db.get(user,"nickname"));out.put("loginMethod",String.valueOf(Db.get(user,"openid")).startsWith("phone:")?"PHONE":"WECHAT");return ApiResponse.ok(out);}
    @PostMapping("/admin/auth/logout") public ApiResponse<Void> adminLogout(@RequestHeader("token") String token){tokens.revoke(token);return ApiResponse.ok();}
    @PostMapping("/user/auth/logout") public ApiResponse<Void> userLogout(@RequestHeader("authentication") String token){tokens.revoke(token);return ApiResponse.ok();}
    public static class LoginRequest {public String username;public String password;public String code;public String nickname;public String phone;public String loginMethod;}
}
