package com.snapmeal.auth;
import com.snapmeal.common.UnauthorizedException;
import org.springframework.beans.factory.annotation.Value;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;
import javax.crypto.Mac;import javax.crypto.spec.SecretKeySpec;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.Instant;import java.util.Base64;
@Service
public class TokenService {
    private static final long TTL_SECONDS=8*60*60;private final byte[] secret;private final JdbcTemplate jdbc;
    public TokenService(@Value("${sky.security.token-secret}") String secret,JdbcTemplate jdbc){this.secret=secret.getBytes(StandardCharsets.UTF_8);this.jdbc=jdbc;}
    public String issue(long subjectId,String role){long expires=Instant.now().plusSeconds(TTL_SECONDS).getEpochSecond();String payload=subjectId+":"+role+":"+expires+":"+System.nanoTime();String token=encode(payload.getBytes(StandardCharsets.UTF_8))+"."+encode(sign(payload));jdbc.update("insert into auth_session(token_hash,subject_id,role,expires_at,revoked) values(?,?,?,?,0)",hash(token),subjectId,role,java.sql.Timestamp.from(Instant.ofEpochSecond(expires)));return token;}
    public Session verify(String token,String role){try{if(token==null||token.trim().isEmpty())throw new UnauthorizedException("请先登录");String[] parts=token.split("\\.");if(parts.length!=2)throw new UnauthorizedException("登录状态无效或已过期");String payload=new String(Base64.getUrlDecoder().decode(parts[0]),StandardCharsets.UTF_8);byte[] provided=Base64.getUrlDecoder().decode(parts[1]);if(!MessageDigest.isEqual(sign(payload),provided))throw new UnauthorizedException("登录状态无效或已过期");String[] fields=payload.split(":");if(fields.length!=4)throw new UnauthorizedException("登录状态无效或已过期");long id=Long.parseLong(fields[0]);String actualRole=fields[1];long expires=Long.parseLong(fields[2]);if(!actualRole.equals(role)||expires<Instant.now().getEpochSecond())throw new UnauthorizedException("登录状态无效或已过期");Integer active=jdbc.queryForObject("select count(*) from auth_session where token_hash=? and subject_id=? and role=? and revoked=0 and expires_at>current_timestamp",Integer.class,hash(token),id,role);if(active==null||active==0)throw new UnauthorizedException("登录状态无效或已过期");return new Session(id,actualRole,Instant.ofEpochSecond(expires));}catch(UnauthorizedException e){throw e;}catch(Exception e){throw new UnauthorizedException("登录状态无效或已过期");}}
    public void revoke(String token){if(token!=null&&!token.trim().isEmpty())jdbc.update("update auth_session set revoked=1 where token_hash=?",hash(token));}
    private byte[] sign(String payload){try{Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(secret,"HmacSHA256"));return mac.doFinal(payload.getBytes(StandardCharsets.UTF_8));}catch(Exception e){throw new IllegalStateException("令牌签名失败",e);}}
    private String encode(byte[] value){return Base64.getUrlEncoder().withoutPadding().encodeToString(value);}
    private String hash(String token){try{byte[] bytes=MessageDigest.getInstance("SHA-256").digest(token.getBytes(StandardCharsets.UTF_8));StringBuilder value=new StringBuilder();for(byte b:bytes)value.append(String.format("%02x",b));return value.toString();}catch(Exception e){throw new IllegalStateException("令牌摘要失败",e);}}
    public static class Session {private final long subjectId;private final String role;private final Instant expiresAt;Session(long id,String role,Instant expires){this.subjectId=id;this.role=role;this.expiresAt=expires;}public long getSubjectId(){return subjectId;}public String getRole(){return role;}public Instant getExpiresAt(){return expiresAt;}}
}
