package com.snapmeal.user;
import com.snapmeal.auth.AuthInterceptor; import com.snapmeal.common.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.web.bind.annotation.*; import javax.servlet.http.HttpServletRequest; import java.math.BigDecimal; import java.util.*;
@RestController @RequestMapping("/api/user/cart")
public class CartController {
    private final JdbcTemplate jdbc;public CartController(JdbcTemplate jdbc){this.jdbc=jdbc;}private long uid(HttpServletRequest r){return ((Number)r.getAttribute(AuthInterceptor.SUBJECT_ID)).longValue();}
    @GetMapping public ApiResponse<List<Map<String,Object>>> list(HttpServletRequest r){return ApiResponse.ok(jdbc.queryForList("select * from shopping_cart where user_id=? order by create_time",uid(r)));}
    @PostMapping("/items") public ApiResponse<Void> add(HttpServletRequest req,@RequestBody Item r){long user=uid(req);String table=r.dishId!=null?"dish":"setmeal";Long id=r.dishId!=null?r.dishId:r.setmealId;if(id==null)throw new BusinessException("请选择菜品或套餐");List<Map<String,Object>> goods=jdbc.queryForList("select name,image,price,status from "+table+" where id=?",id);if(goods.isEmpty()||Db.intValue(goods.get(0),"status")!=1)throw new BusinessException("商品不存在或已停售");List<Map<String,Object>> existing=jdbc.queryForList("select id from shopping_cart where user_id=? and "+(r.dishId!=null?"dish_id":"setmeal_id")+"=?",user,id);if(existing.isEmpty()){Map<String,Object> g=goods.get(0);jdbc.update("insert into shopping_cart(user_id,dish_id,setmeal_id,dish_flavor,name,image,amount,number) values(?,?,?,?,?,?,?,1)",user,r.dishId,r.setmealId,r.flavor,Db.get(g,"name"),Db.get(g,"image"),Db.get(g,"price"));}else jdbc.update("update shopping_cart set number=number+1 where id=?",Db.get(existing.get(0),"id"));return ApiResponse.ok();}
    @PatchMapping("/items/{id}") public ApiResponse<Void> quantity(HttpServletRequest req,@PathVariable long id,@RequestParam int number){if(number<=0)jdbc.update("delete from shopping_cart where id=? and user_id=?",id,uid(req));else jdbc.update("update shopping_cart set number=? where id=? and user_id=?",number,id,uid(req));return ApiResponse.ok();}
    @DeleteMapping public ApiResponse<Void> clear(HttpServletRequest req){jdbc.update("delete from shopping_cart where user_id=?",uid(req));return ApiResponse.ok();}
    public static class Item {public Long dishId;public Long setmealId;public String flavor;}
}
